# Generated by Django 5.0.14 on 2026-09-29 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event_type', models.CharField(choices=[('page_view', 'Просмотр страницы'), ('thread_view', 'Просмотр темы'), ('post_created', 'Создан пост'), ('thread_created', 'Создана тема'), ('reaction_added', 'Реакция'), ('search', 'Поиск'), ('login', 'Вход'), ('register', 'Регистрация')], db_index=True, max_length=64, verbose_name='Тип события')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='event_type_created_idx'), models.Index(fields=['user', '-created_at'], name='event_user_idx')],
            },
        ),
    ]
