# Generated by Django 5.0.14 on 2026-09-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=100, verbose_name='Событие')),
                ('topic', models.CharField(db_index=True, max_length=100, verbose_name='Топик')),
                ('payload', models.JSONField(default=dict, verbose_name='Данные')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('last_error', models.CharField(blank=True, default='', max_length=500, verbose_name='Последняя ошибка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Событие outbox',
                'verbose_name_plural': 'События outbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sent_at', 'created_at'], name='outbox_pending_idx')],
            },
        ),
    ]
