# Generated by Django 5.0.14 on 2026-09-29 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='Описание')),
                ('accent', models.CharField(default='#7dd3a0', max_length=9, verbose_name='Акцентный цвет')),
                ('icon', models.CharField(blank=True, default='', max_length=8, verbose_name='Иконка')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт для новых тем')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_forums', to=settings.AUTH_USER_MODEL, verbose_name='Модератор раздела')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forums.forum', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['parent', 'order'], name='forum_parent_order_idx')],
            },
        ),
    ]
