# Generated by Django 5.0.14 on 2026-09-29 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('action', models.CharField(choices=[('post.hide', 'Скрыть пост'), ('post.delete', 'Удалить пост'), ('thread.delete', 'Удалить тему'), ('thread.lock', 'Закрыть тему'), ('thread.unlock', 'Открыть тему'), ('thread.pin', 'Закрепить тему'), ('thread.unpin', 'Открепить тему'), ('thread.move', 'Перенести тему'), ('user.ban', 'Забанить'), ('user.unban', 'Разбанить'), ('user.warn', 'Предупредить'), ('flag.resolve', 'Обработать жалобу'), ('flag.reject', 'Отклонить жалобу')], max_length=64, verbose_name='Действие')),
                ('target_type', models.CharField(blank=True, default='', max_length=16, verbose_name='Тип цели')),
                ('target_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID цели')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='audit_actor_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('reason', models.CharField(blank=True, default='', max_length=1000)),
                ('duration', models.CharField(choices=[('1h', '1 час'), ('1d', '1 день'), ('7d', '7 дней'), ('30d', '30 дней'), ('forever', 'Навсегда')], default='1d', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('lifted_at', models.DateTimeField(blank=True, null=True, verbose_name='Снят в')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_bans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бан',
                'verbose_name_plural': 'Баны',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='ban_user_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('target_type', models.CharField(choices=[('post', 'Пост'), ('thread', 'Тема'), ('user', 'Пользователь')], max_length=16, verbose_name='Тип цели')),
                ('target_id', models.BigIntegerField(verbose_name='ID цели')),
                ('reason', models.CharField(choices=[('spam', 'Спам'), ('abuse', 'Оскорбление'), ('offtopic', 'Офтоп'), ('bot', 'Бот'), ('other', 'Другое')], max_length=32, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, default='', max_length=1000, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], db_index=True, default='open', max_length=16, verbose_name='Статус')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решено в')),
                ('moderator_comment', models.TextField(blank=True, default='', max_length=1000)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL, verbose_name='Решил модератор')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='flag_status_created_idx'), models.Index(fields=['target_type', 'target_id'], name='flag_target_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='flag',
            constraint=models.UniqueConstraint(fields=('reporter', 'target_type', 'target_id'), name='unique_reporter_target'),
        ),
    ]
