# Generated by Django 5.0.14 on 2026-09-29 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='URL')),
                ('usage_count', models.IntegerField(db_index=True, default=0, verbose_name='Использований')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['-usage_count'], name='tag_usage_idx')],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалён в')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL')),
                ('body', models.TextField(verbose_name='Тело (markdown)')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='Тело (HTML)')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, verbose_name='Закреплена')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('is_draft', models.BooleanField(db_index=True, default=False, verbose_name='Черновик')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='Постов')),
                ('reactions_count', models.PositiveIntegerField(default=0, verbose_name='Реакций')),
                ('last_activity_at', models.DateTimeField(db_index=True, verbose_name='Активность')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='forums.forum', verbose_name='Раздел')),
                ('tags', models.ManyToManyField(blank=True, related_name='threads', to='threads.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['-is_pinned', '-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Черновик темы',
                'verbose_name_plural': 'Черновики тем',
            },
        ),
        migrations.CreateModel(
            name='ThreadEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_edits', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='threads.thread')),
            ],
            options={
                'verbose_name': 'Версия темы',
                'verbose_name_plural': 'Версии тем',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='threads.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка на тему',
                'verbose_name_plural': 'Подписки на темы',
            },
        ),
        migrations.AddField(
            model_name='thread',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_threads', through='threads.ThreadSubscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AddConstraint(
            model_name='threaddraft',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_thread_draft'),
        ),
        migrations.AddIndex(
            model_name='threadsubscription',
            index=models.Index(fields=['user', '-created_at'], name='sub_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='threadsubscription',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='unique_thread_subscription'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['forum', '-last_activity_at'], name='thread_forum_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['-created_at'], name='thread_created_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['-reactions_count'], name='thread_reactions_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['is_pinned', '-last_activity_at'], name='thread_pinned_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['author', '-created_at'], name='thread_author_idx'),
        ),
    ]
