# Generated by Django 5.0.14 on 2026-09-29 11:37

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('icon', models.CharField(blank=True, default='🏅', max_length=8)),
                ('kind', models.CharField(choices=[('threads', 'Темы'), ('posts', 'Посты'), ('reactions', 'Реакции'), ('reputation', 'Репутация'), ('special', 'Особые')], default='special', max_length=16)),
                ('threshold', models.PositiveIntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ачивка',
                'verbose_name_plural': 'Ачивки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Имя пользователя')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email подтверждён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Регистрация')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалён в')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='accounts.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ачивка пользователя',
                'verbose_name_plural': 'Ачивки пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, default='', max_length=500, verbose_name='О себе')),
                ('location', models.CharField(blank=True, default='', max_length=64, verbose_name='Локация')),
                ('website', models.URLField(blank=True, default='', verbose_name='Сайт')),
                ('reputation', models.IntegerField(default=0, verbose_name='Репутация')),
                ('rank', models.CharField(choices=[('newbie', 'Newbie'), ('member', 'Member'), ('veteran', 'Veteran'), ('legend', 'Legend'), ('moderator', 'Moderator')], default='newbie', max_length=16, verbose_name='Ранг')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Был онлайн')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=8)),
                ('show_online_status', models.BooleanField(default=True, verbose_name='Показывать онлайн-статус')),
                ('notify_replies', models.BooleanField(default=True, verbose_name='Уведомлять об ответах')),
                ('notify_mentions', models.BooleanField(default=True, verbose_name='Уведомлять об упоминаниях')),
                ('notify_reactions', models.BooleanField(default=True, verbose_name='Уведомлять о реакциях')),
                ('threads_count', models.PositiveIntegerField(default=0, verbose_name='Тем создано')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='Постов написано')),
                ('reactions_received', models.PositiveIntegerField(default=0, verbose_name='Получено реакций')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('email_verification', 'Подтверждение email'), ('password_reset', 'Сброс пароля')], max_length=32)),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Токен верификации',
                'verbose_name_plural': 'Токены верификации',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='user_joined_idx'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['rank'], name='profile_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-reputation'], name='profile_reputation_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['user', 'purpose'], name='token_user_purpose_idx'),
        ),
    ]
