# Generated by Django 5.0.14 on 2026-09-29 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалён в')),
                ('body', models.TextField(verbose_name='Тело (markdown)')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='Тело (HTML)')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Редактирован')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Отредактирован')),
                ('reactions_count', models.PositiveIntegerField(default=0, verbose_name='Реакций')),
                ('is_first_in_thread', models.BooleanField(default=False, verbose_name='Первый пост темы')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='posts.post', verbose_name='Цитируемый пост')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='threads.thread', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Исходное имя')),
                ('content_type', models.CharField(max_length=100, verbose_name='MIME')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='posts.post')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PostEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('body', models.TextField(blank=True, default='')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_edits', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='posts.post')),
            ],
            options={
                'verbose_name': 'Версия поста',
                'verbose_name_plural': 'Версии постов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['thread', 'created_at'], name='post_thread_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='post_author_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-reactions_count'], name='post_reactions_idx'),
        ),
    ]
