# Generated by Django 5.0.14 on 2026-09-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('path', models.CharField(max_length=255, unique=True, verbose_name='Путь')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, default='', max_length=500, verbose_name='Ключевые слова')),
                ('og_image', models.URLField(blank=True, default='', verbose_name='OG-изображение')),
                ('canonical', models.CharField(blank=True, default='', max_length=255, verbose_name='Canonical')),
                ('robots', models.CharField(blank=True, default='index, follow', max_length=100, verbose_name='Robots')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('priority', models.FloatField(default=0.7, verbose_name='Приоритет в sitemap')),
            ],
            options={
                'verbose_name': 'SEO-запись',
                'verbose_name_plural': 'SEO-записи',
                'ordering': ['-priority', 'path'],
            },
        ),
    ]
