# Generated by Django 5.0.14 on 2026-09-29 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(choices=[('like', '👍 Нравится'), ('fire', '🔥 Огонь'), ('laugh', '😂 Смешно'), ('sad', '😢 Грустно'), ('wow', '😮 Вау')], max_length=16, unique=True, verbose_name='Код')),
                ('emoji', models.CharField(max_length=8, verbose_name='Эмодзи')),
                ('karma_value', models.IntegerField(default=1, verbose_name='Вес репутации')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='reactions.reaction')),
            ],
            options={
                'verbose_name': 'Реакция на пост',
                'verbose_name_plural': 'Реакции на посты',
                'indexes': [models.Index(fields=['post', 'reaction'], name='reaction_post_type_idx'), models.Index(fields=['user', '-created_at'], name='reaction_user_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='postreaction',
            constraint=models.UniqueConstraint(fields=('post', 'user', 'reaction'), name='unique_post_user_reaction'),
        ),
    ]
